# Generated by Django 3.2.6 on 2021-08-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.IntegerField()),
                ('hobby', models.CharField(max_length=100)),
                ('datanascimento', models.DateField()),
            ],
        ),
    ]
